function Lines = Draw_rect (Hsize, Vsize, Center, Color)

Upper_left = Center + [-Hsize/2, Vsize/2];  
Upper_right = Center +[Hsize/2, Vsize/2];
Lower_left = Center - [Hsize/2, Vsize/2];
Lower_right = Center +[Hsize/2, -Vsize/2];

Lines = line('XData', [Upper_left(1), Upper_right(1), Lower_right(1), ...
	Lower_left(1), Upper_left(1)], ...
				 'YData', [Upper_left(2), Upper_right(2), Lower_right(2), ...
	Lower_left(2), Upper_left(2)], 'Color', Color, 'LineStyle', '-', ...
	'LineWidth', 2);
