function [ G ] = G_statistic( hist1, hist2 )
%Calculates G statistic of 2 histograms

G = 2*(sum(sum((hist1.*log(hist1)))) + ...
        sum(sum((hist2.*log(hist2))))) - ...
        (sum(sum(hist1))*log(sum(sum(hist1))) + ...
        sum(sum(hist2))*log(sum(sum(hist2)))) - ...
        sum(sum((hist1+hist2).*log(hist1+hist2))) + ...
        (sum(sum(hist1))+sum(sum(hist2)))*log(sum(sum(hist1))+sum(sum(hist2)));

end

